todo/base/urls.py
from django.urls import path
from .views import (
    TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDelete, TaskCompleteView
)


app_name = 'base'

urlpatterns = [
    path('', TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task_detail'),
    path('task/create/', TaskCreate.as_view(), name='task_create'),
    path('task/<int:pk>/update/', TaskUpdate.as_view(),name='task_update'),
    path('task/<int:pk>/delete/', TaskDelete.as_view(),name='task_delete'),
    path('tasks/<int:pk>/complete/', TaskCompleteView.as_view(), name='task_complete'),
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('base.urls')),
]

todo/users/urls.py
from django.urls import path
from django.contrib.auth.views import (PasswordResetDoneView,
                                       PasswordChangeDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)

from .views import SignUpView, UserLoginView, PasswordsChangeView, logout_user, password_reset

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/',
         logout_user,
         name='logout'),
    path('login/',
         UserLoginView.as_view(),
         name='login'),
    path('password_change/form/',
          PasswordsChangeView.
          as_view(template_name='users/password_change_form.html'),
          name='password_change_form'),
    path('password_change/done/',
         PasswordChangeDoneView.
         as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/form/',
         password_reset,
         name='password_reset_form'),
    path('password_reset/done/',
         PasswordResetDoneView.
         as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.
         as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.
         as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

     ]

todo/templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-white ">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarExample01">
            <span> <a href="{% url 'base:tasks' %}" > <i class="bi bi-house-door-fill bi-2xl text-warning" style="font-size: 30px"></i></a> </span>
            {% if request.user.is_authenticated %}
            <div class="navbar-nav me-auto mb-2 mb-lg-0">
                <span class="navbar-text text-danger"> {{request.user }} </span>
            </div>
            <div class="navbar-nav">
                <li class="nav-item"> <a class="nav-link" href="{% url 'users:logout' %}">Logout</a> </li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'users:password_change_form' %}">Change Pw</a> </li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'users:password_reset_form' %}">Reset Pw</a> </li>
            </div>
            {% else %}
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"> <a class="nav-link" href="{% url 'users:login' %}">Login</a> </li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'users:signup' %}">Register</a> </li>
            </ul>
            {% endif %}
            
        </div>
    </div>
</nav>