todo/base/urls.py
from django.urls import path
from .views import (
    TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDelete, TaskCompleteView
)


app_name = 'base'

urlpatterns = [
    path('', TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task_detail'),
    path('task/create/', TaskCreate.as_view(), name='task_create'),
    path('task/<int:pk>/update/', TaskUpdate.as_view(),name='task_update'),
    path('task/<int:pk>/delete/', TaskDelete.as_view(),name='task_delete'),
    path('tasks/<int:pk>/complete/', TaskCompleteView.as_view(), name='task_complete'),
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('base.urls')),
]

todo/base/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Task(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='tasks'
    )
    title = models.CharField(max_length=200, verbose_name='Title', help_text='Set a title')
    description = models.TextField(null=True, help_text='Add descriprion')
    complete = models.BooleanField(default=False, help_text='Task is complete ?')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        ordering = ('complete', '-created')

todo/base/forms.py
from django import forms

from .models import Task, User

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'complete')
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title', 'class': 'form-control'}),
            'description': forms.TextInput(attrs={'placeholder': 'Description', 'class': 'form-control'}),
            'complete': forms.CheckboxInput(attrs={'class': 'required form-check-input'})
        }


class TaskCompleteForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['complete']
        

todo/base/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView

from .models import Task
from .forms import TaskCompleteForm, TaskForm
from .utils import TaskRequiredMixin

class TaskList(ListView):
    model = Task
    context_object_name = 'tasks'

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            return Task.objects.filter(user=user)
        return Task.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_input = self.request.GET.get('search-area') or ''

        if search_input:
            context['tasks'] = context['tasks'].filter(
                title__icontains=search_input
            )
        context['search_input'] = search_input
        return context


class TaskCompleteView(FormView):
    form_class = TaskCompleteForm
    success_url = reverse_lazy('base:tasks')
    pk_url_kwarg = 'pk'

    def form_valid(self, form):
        task = get_object_or_404(Task, id=self.kwargs['pk'])
        task.complete = not task.complete
        task.save()
        return super().form_valid(form)


class TaskDetail(TaskRequiredMixin, DetailView):
    model = Task
    template_name = 'base/task_detail.html'
    context_object_name = 'task'
    pk_url_kwarg = 'pk'


class TaskCreate(TaskRequiredMixin, CreateView):
    form_class = TaskForm
    template_name = 'base/task_create.html'
    success_url = reverse_lazy('base:tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TaskUpdate(TaskRequiredMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'base/task_create.html'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('base:tasks')

class TaskDelete(TaskRequiredMixin, DeleteView):
    model = Task
    template_name = 'base/task_delete.html'
    success_url = reverse_lazy('base:tasks')
    context_object_name = 'task'

todo/templates/base/task_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block  title %}Form{% endblock  %}

{% block content %}
{% load user_filters %}


<h3 class=" mt-3 mb-4 pb-3 text-center"> Task Create </h3>
<div class="overflow-auto">
<form method="POST" class="blueForms" action="">
    <div class="form-outline">
        {% csrf_token %}
        <ul>
        {% for field in form %}
            <p>
            <small id="id_text-help" class="form-text text-muted">
                {{field.help_text|safe}}
            </small>   
            {{ field }}
            </p>
        {% endfor %}
        </ul>
        <div class=" text-end p-3">
        <input type="submit" class="btn btn-info ms-2" value="Submit">
        </div>
    </div>
</form>
</div>
{% endblock content %}

todo/templates/base/task_delete.html
{% extends 'base.html' %}

{% block  title %}Delete confirm{% endblock  %}

{% block content %}
<div class="vh-100">

<form method="POST" action="">
    {% csrf_token %}
    <div class="lead mb-12 text-center">
    <p> Are you sure you want to delete <i class='text-danger'>{{task}}</i> ?</p>
    </div>
    
    <input type="submit" class="btn btn-danger ms-2" value="Delete">
</form>
</div>
{% endblock content %}

todo/templates/base/task_detail.html
{% extends 'base.html' %}

{% block  title %}Task {{task}}{% endblock  %}

{% block content %}
<div class="vh-90" >
<h1 class="mt-3 mb-4 pb-3 text-center"> Task </h1>
    <div class="lead text-center">
    {{task.title}}
    </div>
<hr class="hr hr-blurry" />
<div class="text-justify display-6 text-center"> Description
</div>
<div class="lead mb-12">
        {{task.description}}
</div>
</div>
{% endblock content %}

todo/templates/base/task_list.html
{% extends 'base.html' %}

{% block  title %}My Tasks{% endblock  %}

{% block content %}
<form method="GET" class="d-flex justify-content-center align-items-center mb-4">
    <div class="form-outline flex-fill">
        <input type="text" id="search" class="form-control" name="search-area" value="{{search_input}}" placeholder="Task..."/>
    </div>
    <input class="btn btn-info ms-2" type="submit" value="Search"/>
    
</form>
<table class="table table-striped">
<tbody>
<div class="overflow-auto">
    {% for task in tasks %}
    <tr>
        <li class="list-group-item d-flex align-items-center border-0 mb-2 rounded"
        style="background-color: #f4f6f7;">
            {% if task.complete %}
            <td class="card-text link-unstyled position-relative" style="text-decoration: line-through;">
            {% else %}
            <td class="card-text link-unstyled position-relative">
            {% endif %}
                {{ task }}
                <a href="{% url 'base:task_detail' task.id %}" class=" stretched-link"> </a>
            </td>
            <th><a href="{% url 'base:task_update' task.id %}" > <i class="bi bi-pencil-fill text-info m-3"></i></a> </th>
            <td><a href="{% url 'base:task_delete' task.id %}"> <i class="bi bi-trash-fill text-danger m-3"></i></a> </td>
            <td>
                <form method="POST" action="{% url 'base:task_complete' task.id %}">
                    {% csrf_token %}
                    <input type="checkbox" name="complete" id="{{ task.id }}" {% if task.complete %}checked{% endif %} onclick="this.form.submit()">
                </form>
            </td>
        </li>
        {% empty %}
            <p>No items in list</p>
    </tr>
    {% endfor %}
</div>
</tbody>
</table>
<div class=" text-end p-3">
<a href="{% url 'base:task_create'%}" class="btn btn-warning ms-2" >Add Task </a>
</div>
{% endblock content %}